/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_bobbyz_helloworldvcppandroidapp_CommonLibrary */

#ifndef _Included_dk_bobbyz_helloworldvcppandroidapp_CommonLibrary
#define _Included_dk_bobbyz_helloworldvcppandroidapp_CommonLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_bobbyz_helloworldvcppandroidapp_CommonLibrary
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dk_bobbyz_helloworldvcppandroidapp_CommonLibrary_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
