/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_bobbyz_helloworldcpp_SharedLibrary */

#ifndef __cplusplus
#define __cplusplus
#endif

#ifndef _Included_dk_bobbyz_helloworldcpp_SharedLibrary
#define _Included_dk_bobbyz_helloworldcpp_SharedLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_bobbyz_helloworldcpp_SharedLibrary
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dk_bobbyz_helloworldcpp_SharedLibrary_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
